{
  config,
  ...
}:
{
  programs.ssh = {
    enable = true;
    addKeysToAgent = "yes";
    matchBlocks = {
      "*" = {
        identityFile = "~/.ssh/ssh_host_ed25519_key";
      };
    };
    includes = [
      "~/.ssh/other_config"
    ];
  };

  # Since the host key is generated by the system, we need to
  # copy it to the user's home directory
  # The system will be single-user, so this is not a problem
  home.file = {
    ".ssh/ssh_host_ed25519_key" = {
      source = config.lib.file.mkOutOfStoreSymlink "/etc/ssh/ssh_host_ed25519_key";
    };
    ".ssh/ssh_host_ed25519_key.pub" = {
      source = config.lib.file.mkOutOfStoreSymlink "/etc/ssh/ssh_host_ed25519_key.pub";
    };
  };
}
