global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

certificateResolvers:
  digitalocean:
    email: "me@wetrustinprize.com"
    storage: /var/traefik/certs/digitalocean-acme.json
    caServer: 'https://acme-v02.api.letsencrypt.org/directory'
    keyType: EC256
    dnsChallenge:
      provider: digitalocean
      resolvers:
        - "1.1.1.1:53"
        - "8.8.8.8:53"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false