{
  pkgs,
  system,
  inputs,
  lib,
  nixpkgs,
  username,
  nix-colors,
  config,
  ...
}:
{
  nixpkgs = {
    config = {
      allowUnfree = true;
    };
    overlays = [
      inputs.nix-your-shell.overlays.default
    ];
  };

  colorScheme = nix-colors.colorSchemes.nord;

  home.username = username;

  home.packages = with pkgs; [
    nixfmt-rfc-style
    pinentry
    gh
  ];

  programs.ssh = {
    enable = true;
    addKeysToAgent = "yes";
    includes = [
      "~/.ssh/other_config"
    ];
  };

  # Since the host key is generated by the system, we need to
  # copy it to the user's home directory
  # The system will be single-user, so this is not a problem
  home.file.".ssh/ssh_host_ed25519_key" = {
    source = config.lib.file.mkOutOfStoreSymlink "/etc/ssh/ssh_host_ed25519_key";
  };
  home.file.".ssh/ssh_host_ed25519_key.pub" = {
    source = config.lib.file.mkOutOfStoreSymlink "/etc/ssh/ssh_host_ed25519_key.pub";
  };

  programs.git = {
    enable = true;
    userEmail = "me@wetrustinprize.com";
    userName = "wetrustinprize";
  };

  sops = {
    age.keyFile = "${config.home.homeDirectory}/.age.key";
    defaultSopsFile = ../../secrets.yaml;
  };

  require = [
    ./modules/shell.nix
    ./modules/yazi.nix
  ];

  home.stateVersion = "24.05";
}
